- id: '1566051632327'
  alias: MQTT zasuvka 1 zapnuti
  trigger:
  - payload: 'on'
    platform: mqtt
    topic: homehub/zasuvka1/turn
  condition: []
  action:
  - data:
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    service: switch.turn_on
- id: '1566052723231'
  alias: MQTT zasuvka1 vypnuti
  trigger:
  - payload: 'off'
    platform: mqtt
    topic: homehub/zasuvka1/turn
  condition: []
  action:
  - data:
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    service: switch.turn_off
- id: '1566056490420'
  alias: PIR Vchod to MQTT
  trigger:
  - entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    platform: state
    to: '8'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: homehub/vchod/motion
      payload: 'on'
- id: '1566056999920'
  alias: PIR Vchod to MQTT
  trigger:
  - entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    platform: state
    to: '0'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: homehub/vchod/motion
      payload: 'off'
- id: '1566150599718'
  alias: MQTT zasuvka 2 zapnuti
  trigger:
  - payload: 'on'
    platform: mqtt
    topic: homehub/zasuvka2/turn
  condition: []
  action:
  - data:
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
    service: switch.turn_on
- id: '1566150599818'
  alias: MQTT zasuvka2 vypnuti
  trigger:
  - payload: 'off'
    platform: mqtt
    topic: homehub/zasuvka2/turn
  condition: []
  action:
  - data:
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
    service: switch.turn_off
- id: '1566150600018'
  alias: MQTT Zasuvka1 vykon
  trigger:
  - entity_id: sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power
    platform: state
  condition: []
  action:
  - data:
      payload_template: "{{ states.sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power.state }}"
      topic: homehub/zasuvka1/power
    service: mqtt.publish
- id: '1566150600118'
  alias: MQTT Zasuvka2 vykon
  trigger:
  - entity_id: sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power_2
    platform: state
  condition: []
  action:
  - data:
      payload_template: "{{ states.sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power_2.state }}"
      topic: homehub/zasuvka2/power
    service: mqtt.publish
