### jsn-sr04t.yaml

### sensor classes #####################################
# None: Generic sensor. This is the default and doesn’t need to be set.
# battery: Percentage of battery that is left.
# humidity: Percentage of humidity in the air.
# illuminance: The current light level in lx or lm.
# signal_strength: Signal strength in dB or dBm.
# temperature: Temperature in °C or °F.
# power: Power in W or kW.
# pressure: Pressure in hPa or mbar.
# timestamp: Datetime object or timestamp string.
# current: Current in A.
# energy: Energy in Wh or kWh.
# power_factor: Power Factor in %.
# voltage: Voltage in V.

- platform: mqtt
  name: 'Water level (Studna)'
  state_topic: 'gardenopenhub/studna/distance'
  value_template: '{{(400 - value|float)|round(1)}}'
  unit_of_measurement: 'cm'
