### homehub.yaml

# None: Generic on/off. This is the default and doesn’t need to be set.
# battery: on means low, off means normal
# battery_charging: on means charging, off means not charging
# cold: on means cold, off means normal
# connectivity: on means connected, off means disconnected
# door: on means open, off means closed
# garage_door: on means open, off means closed
# gas: on means gas detected, off means no gas (clear)
# heat: on means hot, off means normal
# light: on means light detected, off means no light
# lock: on means open (unlocked), off means closed (locked)
# moisture: on means moisture detected (wet), off means no moisture (dry)
# motion: on means motion detected, off means no motion (clear)
# moving: on means moving, off means not moving (stopped)
# occupancy: on means occupied, off means not occupied (clear)
# opening: on means open, off means closed
# plug: on means device is plugged in, off means device is unplugged
# power: on means power detected, off means no power
# presence: on means home, off means away
# problem: on means problem detected, off means no problem (OK)
# safety: on means unsafe, off means safe
# smoke: on means smoke detected, off means no smoke (clear)
# sound: on means sound detected, off means no sound (clear)
# vibration: on means vibration detected, off means no vibration (clear)
# window: on means open, off means closed

- platform: mqtt
  name: Terarrium Heating
  state_topic: "homehub/zasuvka1/turn"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: Terarrium Light
  state_topic: "homehub/zasuvka2/turn"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: Home Entrance Movement
  state_topic: "homehub/vchod/motion"
  payload_on: "on"
  payload_off: "off"
